config/routes.rb
ShpostDistribution::Application.routes.draw do
  resources :order_detail_logs

  root 'welcome#index'

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :user_logs, only: [:index, :show, :destroy]

  resources :units do
    resources :users, :controller => 'unit_users'
  end

  resources :users do
    member do
      get 'to_reset_pwd'
      patch 'reset_pwd'
      post 'lock' => 'users#lock'
      post 'unlock' => 'users#unlock'
    end
    resources :roles, :controller => 'user_roles'
  end

  resources :up_downloads do
    collection do 
      get 'up_download_import'
      post 'up_download_import' => 'up_downloads#up_download_import'
      
      get 'to_import'
      
      
    end
    member do
      get 'up_download_export'
      post 'up_download_export' => 'up_downloads#up_download_export'
    end
  end

  resources :import_files do
    collection do
      get 'image_index'
    end
    
    member do 
      get 'download'
      post 'download' => 'import_files#download'
    end
  end

  resources :suppliers do
    collection do 
      get 'supplier_import'
      post 'supplier_import' => 'suppliers#supplier_import'
      
    end

    member do
      get 'set_valid'
      get 'contracts_upload'
      post 'contracts_upload' => 'suppliers#contracts_upload'
      get 'contracts_show'
      delete 'delete_contracts'
    end
   
  end

  resources :commodities do
    collection do 
      get 'commodity_import'
      post 'commodity_import' => 'commodities#commodity_import'
    end

    member do
      get 'cover_upload'
      post 'cover_upload' => 'commodities#cover_upload'
      get 'cover_show'
      get 'set_on_sell'
    end
  end

  resources :supplier_autocom do
    collection do
      get 'c_autocomplete_supplier_name'
        
    end
  end

  resources :orders do
    collection do
      get 'fresh'
      get 'pending'
      get 'checking'
      get 'declined'
      get 'rechecking'
      get 'receiving'
      get 'look'
    end

    resources :order_details, ony: [:index, :new, :create]

    member do
      get 'commodity_choose'
      get 'to_check'
    end
  end

  resources :order_details do
    collection do
      get 'pending'
      get 'checking'
      get 'declined'
      get 'rechecking'
      get 'receiving'
      get 'look'
    end
    member do
      post 'to_check'
      post 'to_recheck'
      post 'check_decline'
      post 'place'
      post 'recheck_decline'
      post 'confirm'
      post 'cancel'
      get 'read_log'
    end
  end

  match "/shpost_distribution/reports/order_report" => "reports#order_report", via: [:get, :post]
  match "/shpost_distribution/reports/supplier_report" => "reports#supplier_report", via: [:get, :post]

end

app/models/import_file.rb
class ImportFile < ApplicationRecord 
	belongs_to :user
	belongs_to :unit
	belongs_to :symbol, polymorphic: true

	CATEGORY = {commodity: '商品', supplier: '供应商'}

	def self.img_upload_path(file, symbol, category)
		if !file.original_filename.empty?
			direct = "/public/pic/#{category}/"
			filename = "#{Time.now.to_i}_#{file.original_filename}"

	  	    if !File.exist?("#{Rails.root}/public/pic/")
	          Dir.mkdir("#{Rails.root}/public/pic/")          
	        end
	        if !File.exist?("#{Rails.root}/public/pic/#{category}/")
	          Dir.mkdir("#{Rails.root}/public/pic/#{category}/") 
	        end
	        if !symbol.blank?
		    	if !File.exist?("#{Rails.root}/public/pic/#{category}/#{symbol.id}/")
		          Dir.mkdir("#{Rails.root}/public/pic/#{category}/#{symbol.id}/") 
		        end
		    	direct = "#{direct}#{symbol.id}/"
		    else
		    	if !File.exist?("#{Rails.root}/public/pic/#{category}/zip/")
			    	Dir.mkdir("#{Rails.root}/public/pic/#{category}/zip/") 
			    end
			    direct = "#{direct}zip/"
			end

		    file_path = direct + filename
		    File.open(Rails.root.to_s + file_path, "wb") do |f|
		      f.write(file.read)
		    end
		    file_path
		end
	end

	def self.image_import(file_path, symbol, user, category)
		ori_file_name = File.basename(file_path)
		file_name = File.basename(file_path, "r:ISO-8859-1")
        file_ext = File.extname(file_name)
        size = File.size(Rails.root.to_s + file_path) 

        import_file = ImportFile.create! file_name: file_name, file_path: File.join(file_path.split(ori_file_name), file_name), user_id: user.id, unit_id: user.unit.id, file_ext: file_ext, size: size, symbol_id: symbol.blank? ? nil : symbol.id, category: category, symbol_type: symbol.blank? ? nil : symbol.class.to_s

        return import_file
    end

	def image_destroy!
		file_path = Rails.root.to_s + self.file_path
		
	    if File.exist?(file_path)
	      File.delete(file_path)
	    end
	    
	    self.destroy!
	end

	def self.decompress(file_path, zip_direct, pic_direct, user, category)
		commodity_no = []
		desc = ""
		file_path = Rails.root.to_s + file_path
		
		Zip::File.open(file_path, "r:ISO-8859-1") do |zip|  
            zip.each do |folder| 
            	folder.extract(File.join(zip_direct,folder::name))  
                commodity_no << (folder::name).split('/')[0]
            end
            commodity_no.uniq.each do |f|
            	symbol = Commodity.find_by(no: f)
            	if !File.exist?("#{Rails.root}#{pic_direct}#{symbol.id}/")
					Dir.mkdir("#{Rails.root}#{pic_direct}#{symbol.id}/") 
				end
            	if !symbol.blank? and symbol.category.eql?category             
	                Dir.foreach(folder_direct = File.join(zip_direct,f)) do |pic|
	                	if pic !="." and pic !=".."
	                		if !(pic.include?('.jpg') or pic.include?('.jpeg') or pic.include?('.png') or pic.include?('.bmp'))
	                			desc += ",图片"+pic+"格式不正确"
	                			next
	                		end
	                		if (File.size(File.join(folder_direct,pic))/1024/1024) > I18n.t("pic_upload_param.pic_size")
	                			desc += ",图片"+pic+"大于#{I18n.t("pic_upload_param.pic_size")}M"
	                			next
	                		end	
		                    FileUtils.cp_r(File.join(folder_direct,pic), "#{Rails.root}#{pic_direct}#{symbol.id}/")
		                    new_pic_name = "#{Time.now.to_i}_#{pic}"
		                    File.rename("#{Rails.root}#{pic_direct}#{symbol.id}/#{pic}", "#{Rails.root}#{pic_direct}#{symbol.id}/#{new_pic_name}")
		                    self.image_import(File.join("#{pic_direct}#{symbol.id}/",new_pic_name), symbol, user, symbol.category)
		                end
	                end
	            else
	            	desc += ",文件夹"+f+"找不到对应商品大类的商品"
	            end
                FileUtils.rm_r(File.join(zip_direct,f))
            end
        end
        return desc
	end

	def img_relative_path
		file_path = self.file_path
		start = file_path.index("/pic")
		relative_path = file_path[start, file_path.length-1]
		
		return relative_path
	end

	def absolute_path
		self.file_path.blank? ? nil : Rails.root.to_s + self.file_path
	end

	
end

app/controllers/import_files_controller.rb
class ImportFilesController < ApplicationController
  load_and_authorize_resource
  user_logs_filter only: [:download, :import], symbol: :file_name, operation: :operation, object: :ImportFile

  def index
    @import_files_grid = initialize_grid(@import_files,
         :order => 'import_files.created_at',
         :order_direction => 'desc')
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @import_file.save
        format.html { redirect_to @import_file, notice: I18n.t('controller.create_success_notice', model: '信息导入结果') }
        format.json { render action: 'show', status: :created, location: @import_file }
      else
        format.html { render action: 'new' }
        format.json { render json: @import_file.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
    @operation = "destroy"
    file_path = @import_file.file_path
    if File.exist?(file_path)
      File.delete(file_path)
    end
    @import_file.destroy
      
    respond_to do |format|
      format.html { redirect_to import_files_path }
      format.json { head :no_content }
    end
  end

  def download
    @operation = "download"
    @file_name = @import_file.file_name
    file_path = @import_file.file_path
        
    if !file_path.blank?
      file_path = Rails.root.to_s + file_path 
      if File.exist?(file_path)
        io = File.open(file_path)
        send_data(io.read, :type => "text/excel;charset=utf-8; header=present",              :filename => @file_name)
        io.close
      else
        redirect_to commodity_import_files_path(@import_file.symbol_id), :notice => '文件不存在，下载失败！'
      end
    end
  end

  def image_index
    @import_files = nil
    @symbol_id = nil
    if !params[:format].blank?
      @symbol_id = params[:format].to_i
      @import_files = ImportFile.where(symbol_id: @symbol_id )
    end
    @import_files_grid = initialize_grid(@import_files,
         :order => 'import_files.created_at',
         :order_direction => 'desc')
  end

  private
    def set_import_file
      @import_file = ImportFile.find(params[:id])
    end

    def import_file_params
      params.require(:import_file).permit(:file_name, :file_path)
    end
end

app/helpers/import_files_helper.rb
module ImportFilesHelper
end

app/views/import_files/_form.html.erb
<%= form_for(@import_file) do |f| %>
  <% if @import_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import_file.errors.count, "error") %> prohibited this import_file from being saved:</h2>

      <ul>
      <% @import_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/import_files/edit.html.erb
<h1>Editing import_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @import_file %> |
<%= link_to 'Back', import_files_path %>

app/views/import_files/image_index.html.erb
<%- model_class = ImportFile -%>
<div class="page-header">
  <h1><%="图片管理"%></h1>
  <div style="float:right">
    <% if category.eql?"commodity" %>
      <% if can? :image_import, Commodity %>
        <%= link_to "上传",to_image_import_commodities_path(@symbol_id), :class => 'btn btn-primary' %>                 
      <% end %>
    <% elsif category.eql?"supplier" %>
      <% if can? :image_import, Supplier %>
      <%= link_to "上传",to_image_import_suppliers_path(@symbol_id), :class => 'btn btn-primary' %>                 
      <% end %>
    <% end %>
  </div>
</div>

<%= grid(@import_files_grid) do |g|
    # g.column do |import_file|
    #   radio_button_tag("ifid","#{import_file.id}",false) 
    # end

    g.column name: model_class.human_attribute_name(:file_name), attribute: 'file_name'

    g.column name: model_class.human_attribute_name(:user_id), attribute: 'id', assoc: :user do |import_file|
      import_file.user.try :name
    end

    g.column name: model_class.human_attribute_name(:file_ext), attribute: 'file_ext'

    g.column name: model_class.human_attribute_name(:size), attribute: 'size' do |import_file|
      import_file.size.blank? ? "" : (import_file.size.to_i/1024).round(0).to_s + "k"
    end

    g.column name: model_class.human_attribute_name(:created_at), attribute: 'created_at' do |import_file|
       import_file.created_at.localtime.to_s(:db)
    end

    g.column do |import_file|
       link_to image_tag(import_file.img_relative_path(true), height: '70', width: '90'), image_path(import_file.img_relative_path(false)), target: '_blank'
    end

    g.column do |import_file|
      if category.eql?"commodity"
      ActiveSupport::SafeBuffer.new << 
        (link_to t('.download', :default => t("helpers.links.download")), image_download_commodity_path(import_file.symbol.blank? ? nil : import_file.symbol.detail, import_file),:method => 'post', :class => 'btn btn-xs btn-primary' if (can? :image_download, Commodity)) << ' ' <<
        (link_to t('.destroy', :default => t("helpers.links.destroy")), image_destroy_commodity_path(import_file.symbol.blank? ? nil : import_file.symbol.detail, import_file), :method => :delete, :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => '确定删除?')) }, :class => 'btn btn-xs btn-danger' if can? :image_destroy, Commodity)
      elsif category.eql?"supplier"
        (link_to t('.download', :default => t("helpers.links.download")), image_download_supplier_path(import_file.symbol.blank? ? nil : import_file.symbol.detail, import_file),:method => 'post', :class => 'btn btn-xs btn-primary' if (can? :image_download, Supplier)) << ' ' <<
        (link_to t('.destroy', :default => t("helpers.links.destroy")), image_destroy_supplier_path(import_file.symbol.blank? ? nil : import_file.symbol.detail, import_file), :method => :delete, :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => '确定删除?')) }, :class => 'btn btn-xs btn-danger' if can? :image_destroy, Supplier) 
      end
    end

  end 
%>

app/views/import_files/index.html.erb
<%- model_class = ImportFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human%></h1>
</div>

<%= grid(@import_files_grid) do |g|
    g.column name: model_class.human_attribute_name(:file_name), attribute: 'file_name'

    g.column name: model_class.human_attribute_name(:user_id), attribute: 'id', assoc: :user do |import_file|
      import_file.user.try :name
    end

    g.column name: model_class.human_attribute_name(:symbol_id), attribute: 'symbol_id'

    g.column name: model_class.human_attribute_name(:symbol_type), attribute: 'symbol_type'

    g.column name: model_class.human_attribute_name(:category), attribute: 'category' do |import_file|
      import_file.category.blank? ? " " : ImportFile::CATEGORY[import_file.category.to_sym]
    end

    g.column name: model_class.human_attribute_name(:file_ext), attribute: 'file_ext'

    g.column name: model_class.human_attribute_name(:size), attribute: 'size' do |import_file|
      import_file.size.blank? ? "" : (import_file.size.to_i/1024).round(0).to_s + "k"
    end

    g.column name: model_class.human_attribute_name(:desc), attribute: 'desc'

    g.column name: model_class.human_attribute_name(:created_at), attribute: 'created_at'do |import_file|
      l import_file.created_at
    end

    g.column do |import_file|
      ActiveSupport::SafeBuffer.new << 
      (link_to t('.download', :default => t("helpers.links.download")), download_import_file_path(import_file),:method => 'post', :class => 'btn btn-xs btn-primary' if (can? :download, import_file) and File.exist?(import_file.absolute_path))
      
      end

  end 
%>

app/views/import_files/new.html.erb
<h1>New import_file</h1>

<%= render 'form' %>

<%= link_to 'Back', import_files_path %>

app/views/import_files/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_import_file_path(@import_file) %> |
<%= link_to 'Back', import_files_path %>