config/routes.rb
ShpostDistribution::Application.routes.draw do
  resources :order_detail_logs

  root 'welcome#index'

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :user_logs, only: [:index, :show, :destroy]

  resources :units do
    resources :users, :controller => 'unit_users'
  end

  resources :users do
    member do
      get 'to_reset_pwd'
      patch 'reset_pwd'
      post 'lock' => 'users#lock'
      post 'unlock' => 'users#unlock'
    end
    resources :roles, :controller => 'user_roles'
  end

  resources :up_downloads do
    collection do 
      get 'up_download_import'
      post 'up_download_import' => 'up_downloads#up_download_import'
      
      get 'to_import'
      
      
    end
    member do
      get 'up_download_export'
      post 'up_download_export' => 'up_downloads#up_download_export'
    end
  end

  resources :import_files do
    collection do
      get 'image_index'
    end
    
    member do 
      get 'download'
      post 'download' => 'import_files#download'
    end
  end

  resources :suppliers do
    collection do 
      get 'supplier_import'
      post 'supplier_import' => 'suppliers#supplier_import'
      
    end

    member do
      get 'set_valid'
      get 'contracts_upload'
      post 'contracts_upload' => 'suppliers#contracts_upload'
      get 'contracts_show'
      delete 'delete_contracts'
    end
   
  end

  resources :commodities do
    collection do 
      get 'commodity_import'
      post 'commodity_import' => 'commodities#commodity_import'
    end

    member do
      get 'cover_upload'
      post 'cover_upload' => 'commodities#cover_upload'
      get 'cover_show'
      get 'set_on_sell'
    end
  end

  resources :supplier_autocom do
    collection do
      get 'c_autocomplete_supplier_name'
        
    end
  end

  resources :orders do
    collection do
      get 'fresh'
      get 'pending'
      get 'checking'
      get 'declined'
      get 'rechecking'
      get 'receiving'
      get 'look'
    end

    resources :order_details, ony: [:index, :new, :create]

    member do
      get 'commodity_choose'
      get 'to_check'
    end
  end

  resources :order_details do
    collection do
      get 'pending'
      get 'checking'
      get 'declined'
      get 'rechecking'
      get 'receiving'
      get 'look'
    end
    member do
      post 'to_check'
      post 'to_recheck'
      post 'check_decline'
      post 'place'
      post 'recheck_decline'
      post 'confirm'
      post 'cancel'
      get 'read_log'
    end
  end

  match "/shpost_distribution/reports/order_report" => "reports#order_report", via: [:get, :post]
  match "/shpost_distribution/reports/supplier_report" => "reports#supplier_report", via: [:get, :post]

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :users, dependent: :destroy
  has_many :units, as: :parent

  # has_many :tarrif_items, dependent: :destroy
  # has_many :tarrif_packages, dependent: :destroy

  validates_presence_of :name, :short_name, :message => '不能为空'
  validates_uniqueness_of :name, :message => '该单位已存在'

  validates_uniqueness_of :short_name, :message => '该缩写已存在'

  # UNIT_LEVEL = {1=>'1',2=>'2',3=>'3'}
  TYPE = {branch: '区分公司', delivery: '寄递事业部', postbuy: '国际邮购'}
  # TYPE_BRANCH = {branch: '区分公司'}
  DELIVERY = Unit.find_by(unit_type: 'delivery') 
  POSTBUY = Unit.find_by(unit_type: 'postbuy') 
  def unit_type_name
    unit_type.blank? ? "" : self.class.human_attribute_name("unit_type_#{unit_type}")
  end
  
  
  
  def can_destroy?
		if self.users.blank?
			return true
		else
			return false
		end
  end
  # def delivery?
  #   (unit_type.eql? 'delivery') ? true : false
  # end
  # def postbuy?
  #   (unit_type.eql? 'postbuy') ? true : false
  # end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  load_and_authorize_resource :unit

  # GET /units
  # GET /units.json
  def index
    #@unit = Unit.all
    @units_grid = initialize_grid(@units, :per_page => params[:page_size])
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    #@unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    respond_to do |format|
      @unit.unit_type = 'branch'
       if @unit.save
        format.html { redirect_to @unit, notice: I18n.t('controller.create_success_notice', model: '单位')}
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: I18n.t('controller.update_success_notice', model: '单位') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    if @unit.can_destroy?
      @unit.destroy
    else
      flash[:alert] = " 该区分公司下存在用户，不可删除。"
    end
    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_unit
      #@unit = Unit.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:no, :name, :desc, :short_name, :tcbd_khdh, :unit_level, :parent_id, :unit_type)
    end
end

app/views/units/_form.html.erb
<%= form_for @unit, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_messages %>
  <div class="control-group">
    <%= f.label :no, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :no, :class => 'text_field', :id => 'no' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <font color="red">(必填)</font>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :id => 'name' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :short_name, :class => 'control-label' %>
    <font color="red">(必填)</font>
    <div class="controls">
      <%= f.text_field :short_name, :class => 'text_field', :id => 'short_name' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desc, :class => 'text_field', :id => 'desc' %>
    </div>
  </div>
 <!--  <div class="control-group">
    <%= f.label :tcbd_khdh, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tcbd_khdh, :class => 'text_field' %>
    </div>
  </div>
 <div hidden class="control-group">
    <%= f.label :unit_type, :class => 'control-label' %>
    <div hidden class="controls">
      <%= f.select(:unit_type, Unit::TYPE.invert) %>
    </div>
  </div> -->

  <!-- <div class="control-group">
    <%= f.label :parent_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:parent_id, Unit.where("level in (1,2)").order(:level,:id).map{|u| [u.name,u.id]})%>
    </div>
  </div>
   -->
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            units_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/units/edit.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/index.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human%></h1>
  <%= render partial: '/layouts/page_size' %>
  <div style="float:right">
    <% if can? :new, Unit %>
      <%= link_to t('.new_branch', :default => t("helpers.links.new_branch")),
                  new_unit_path,
                  :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<%= grid(@units_grid) do |g|
    g.column name: model_class.human_attribute_name(:no), attribute: 'no'

    g.column name: model_class.human_attribute_name(:name), attribute: 'name'  do |unit|
      [unit.name.try(:truncate, 18), {title: unit.name}] end

    g.column name: model_class.human_attribute_name(:short_name), attribute: 'short_name'

    g.column name: model_class.human_attribute_name(:desc), attribute: 'desc'  do |unit|
      [unit.desc.try(:truncate, 18), {title: unit.desc}]
    end
    # g.column name: model_class.human_attribute_name(:tcbd_khdh), attribute: 'tcbd_khdh'

    g.column name: model_class.human_attribute_name(:unit_type), attribute: 'unit_type', allow_multiple_selection: false, custom_filter: Unit::TYPE.invert do |unit| 
      unit.unit_type_name
    end
    
    g.column name: model_class.human_attribute_name(:created_at), attribute: 'created_at' do |unit|
      l unit.created_at
    end
    # g.column name: model_class.human_attribute_name(:parent_id), attribute: 'parent_id' ,custom_filter: Unit.accessible_by(current_ability).map{|u| [u.name,u.id]} do |unit|
    #     unit.parent_id.blank? ? "" : Unit.find_by(id:unit.parent_id).name
    # end

    
    g.column do |unit|
      ActiveSupport::SafeBuffer.new << 
        (link_to t('.edit', :default => t("helpers.links.edit")), edit_unit_path(unit), :class => 'btn btn-xs btn-primary' if can? :update, unit) << ' ' <<
        (link_to t('.destroy', :default => t("helpers.links.destroy")), unit_path(unit), :method => :delete, :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => '确定删除?')) }, :class => 'btn btn-xs btn-danger' if can? :destroy, unit) << ' ' <<
        (link_to t('.users', :default => t("helpers.links.users")), unit_users_path(unit), :class => 'btn btn-xs btn-info' if can? :user, unit) 
    end
  end 
%>

app/views/units/new.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/show.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:no) %>:</strong></dt>
  <dd><%= @unit.no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @unit.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_name) %>:</strong></dt>
  <dd><%= @unit.short_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desc) %>:</strong></dt>
  <dd><%= @unit.desc %></dd>
 <!--  <dt><strong><%= model_class.human_attribute_name(:tcbd_khdh) %>:</strong></dt>
  <dd><%= @unit.tcbd_khdh %></dd> -->
  
 <!--  <dt><strong><%= model_class.human_attribute_name(:parent_id) %>:</strong></dt>
  <dd><%= @unit.parent_id.blank? ? "" : Unit.find_by(id:@unit.parent_id).name %></dd> -->
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              units_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_path(@unit), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_path(@unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '确定删除?')) },
              :class => 'btn btn-danger' %>